const missions=[
 {place:'School Entrance',icon:'🎒',npc:'👦',speaker:'Ayaan',q:'Ayaan drops his pencils. What should Hoorain do?',choices:[['Help pick them up and ask if he is okay',1,1,'Great! A representative notices when someone needs help.'],['Walk past because class is starting',0,0,'Being on time matters, but helping quickly is a kind choice.'],['Tell someone else to help',0,0,'A leader can set the example too.']]},
 {place:'Year 3 Bronze Classroom',icon:'📚',npc:'👧',speaker:'Sara',q:'Sara says the reading corner needs more exciting books. What should Hoorain do first?',choices:[['Listen and write the idea down',1,1,'Excellent listening! Good representatives collect classmates’ ideas.'],['Promise every book will arrive tomorrow',0,0,'Representatives should not promise something they cannot guarantee.'],['Say her own idea is better',0,0,'A representative should make space for everyone’s voice.']]},
 {place:'Classroom Star Hunt',icon:'⭐',npc:'👩‍🏫',speaker:'Ms. Maple',q:'Quick challenge! Collect all 5 Leadership Stars hidden around the classroom.',type:'stars'},
 {place:'Playground',icon:'🌳',npc:'🧒',speaker:'New Student',q:'A new student is standing alone at break. What could Hoorain do?',choices:[['Invite them to join and introduce them to others',0,2,'Kindness bonus! Helping someone feel included makes school better.'],['Ignore them and keep playing',0,0,'Try to notice classmates who may need a friendly welcome.'],['Tell them to find their own friends',0,0,'A small welcome can make a big difference.']]},
 {place:'Lost & Found',icon:'🔎',npc:'👧',speaker:'Aisha',q:'Aisha cannot find her yellow notebook. Can you spot it among the school things?',type:'find'},
 {place:'Class Ideas Board',icon:'💡',npc:'👧',speaker:'Year 3 Bronze',q:'The class has several ideas. How should Hoorain choose what to take to Student Council?',choices:[['Ask the class and represent common priorities',2,0,'Leadership bonus! Representation means carrying the class’s voice.'],['Only choose her personal favourite',0,0,'Her view matters, but she represents the whole class.'],['Choose her best friend’s idea',0,0,'A representative should consider everyone fairly.']]},
 {place:'Library',icon:'📖',npc:'👦',speaker:'Omar',q:'Omar is struggling to reach a book on a high shelf. What should Hoorain do?',choices:[['Offer help or ask the librarian safely',0,2,'Kind and safe! Helping does not mean taking unnecessary risks.'],['Climb the shelf herself',0,0,'Shelves are not for climbing. Ask an adult for safe help.'],['Laugh and walk away',0,0,'A representative should be supportive.']]},
 {place:'School Corridor',icon:'🤝',npc:'👧',speaker:'Maya',q:'Two classmates both want to speak to Hoorain at once. What is the fairest response?',choices:[['Listen to each person in turn',1,1,'Excellent. Fair listening helps everyone feel heard.'],['Only listen to the louder person',0,0,'Being louder should not decide whose voice matters.'],['Ignore both of them',0,0,'Representatives need to make time to listen.']]},
 {place:'Kindness Corner',icon:'❤️',npc:'👩‍🏫',speaker:'Ms. Maple',q:'The class wants a Kindness Corner. What could Hoorain suggest?',choices:[['A place for kind notes and helpful ideas',1,2,'Wonderful! That encourages positive actions from everyone.'],['A board only for her own achievements',0,0,'A shared corner should celebrate and support the whole class.'],['Nothing — kindness cannot be encouraged',0,0,'Small reminders can help build a kind classroom.']]},
 {place:'Playground Star Dash',icon:'🌟',npc:'🧒',speaker:'Playground Monitor',q:'Challenge time! Find 5 Leadership Stars around the playground.',type:'stars'},
 {place:'Lunch Hall',icon:'🍎',npc:'👦',speaker:'Zain',q:'Zain has nowhere to sit at lunch. What should Hoorain do?',choices:[['Invite him to sit with the group',0,2,'A simple invitation can make someone feel welcome.'],['Tell him every seat is taken',0,0,'If there is space, inclusion is the kinder choice.'],['Pretend not to notice',0,0,'Good leaders notice when someone may need support.']]},
 {place:'Eco Station',icon:'♻️',npc:'👧',speaker:'Lina',q:'Lina suggests reducing classroom waste. What should Hoorain do?',choices:[['Ask the class for practical recycling ideas',2,0,'Great leadership! Turn an idea into a plan with the class.'],['Throw the suggestion away',0,0,'Every reasonable idea deserves consideration.'],['Promise the whole school will change today',0,0,'Good leaders make realistic commitments.']]},
 {place:'Sports Area',icon:'⚽',npc:'👦',speaker:'Adam',q:'A game has uneven teams. How can Hoorain help?',choices:[['Help make fair teams so everyone can join',1,1,'Fair play is good leadership and good teamwork.'],['Put all the strongest players together',0,0,'Balanced teams usually make the game fairer.'],['Stop the game completely',0,0,'A small fair adjustment may solve the problem.']]},
 {place:'Quiet Reading Area',icon:'🤫',npc:'👧',speaker:'Noor',q:'Noor says the reading area is too noisy. What should Hoorain do?',choices:[['Listen and suggest a quiet-reading reminder',1,1,'Good solution: listen, then suggest something practical.'],['Tell Noor to leave the library',0,0,'The shared space should work for everyone.'],['Shout for everyone to be quiet',0,0,'A calm reminder is more respectful.']]},
 {place:'Classroom Challenge',icon:'⭐',npc:'👩‍🏫',speaker:'Teacher',q:'Collect another set of 5 stars to show your teamwork!',type:'stars'},
 {place:'Suggestion Box',icon:'📮',npc:'👧',speaker:'Classmate',q:'A classmate is shy about sharing an idea. What can Hoorain do?',choices:[['Offer to put the idea in the suggestion box',1,1,'Excellent! There can be more than one way to have a voice.'],['Tell everyone who suggested it',0,0,'Respecting privacy can help classmates feel safe sharing ideas.'],['Ignore anonymous ideas',0,0,'Good ideas can still matter even when shared quietly.']]},
 {place:'Art Room',icon:'🎨',npc:'👦',speaker:'Yusuf',q:'The class is making a Student Council poster. What should Hoorain encourage?',choices:[['Let several classmates contribute ideas and drawings',1,1,'Teamwork makes the poster belong to the whole class.'],['Do the whole poster herself',0,0,'Leadership includes giving others a chance to contribute.'],['Only use one friend’s ideas',0,0,'A class project should welcome wider participation.']]},
 {place:'Lost & Found Check',icon:'🔎',npc:'👧',speaker:'Aisha',q:'Aisha needs her yellow notebook again for the meeting. Can you find it?',type:'find'},
 {place:'Friendship Bench',icon:'🪑',npc:'🧒',speaker:'New Student',q:'What is the best purpose for a Friendship Bench?',choices:[['A place where someone can sit when they would like a friend',1,2,'Great! It gives children a simple way to ask for company.'],['A seat nobody is allowed to use',0,0,'That would not help anyone make friends.'],['A prize only for representatives',0,0,'The bench should be available to children who need it.']]},
 {place:'Assembly Preparation',icon:'🎤',npc:'👩‍🏫',speaker:'Assembly Teacher',q:'Hoorain has to speak briefly in assembly. What should she do?',choices:[['Prepare a few clear points and practise them',2,0,'Preparation builds confidence and keeps the message clear.'],['Make up everything at the microphone',0,0,'A little preparation usually makes public speaking easier.'],['Speak for as long as possible',0,0,'Clear and concise communication is more effective.']]},
 {place:'Vote for Hoorain Wall',icon:'🗳️',npc:'👧',speaker:'Classmate',q:'A “VOTE FOR HOORAIN” poster is on the wall. What message should it represent?',choices:[['Kindness, listening and representing Year 3 Bronze',2,1,'Exactly! The poster should reflect positive leadership.'],['Being better than everyone else',0,0,'Student leadership is about service, not superiority.'],['Making promises she cannot keep',0,0,'Trust grows from realistic and responsible promises.']]},
 {place:'Leadership Star Finale',icon:'🌟',npc:'👩‍🏫',speaker:'Ms. Maple',q:'Final star challenge! Collect all 5 before the Council meeting.',type:'stars'},
 {place:'Student Council Meeting',icon:'🏫',npc:'👩‍🏫',speaker:'Council Teacher',q:'“What would Year 3 Bronze like us to consider?” How should Hoorain answer?',choices:[['Clearly explain the class idea and why it would help',2,0,'Fantastic! Clear reasons make an idea easier to consider.'],['Say “I forgot” without checking her notes',0,0,'Preparing notes helps a representative speak confidently.'],['Demand everyone agrees immediately',0,0,'Student Council works best through respectful discussion.']]},
 {place:'Council Decision',icon:'✅',npc:'👦',speaker:'Council Member',q:'Not every class idea can be approved immediately. What should Hoorain do?',choices:[['Explain the outcome honestly and keep useful ideas for later',2,1,'Excellent leadership: honest, positive and persistent.'],['Tell the class everything was approved',0,0,'A representative should report outcomes accurately.'],['Become angry with the council',0,0,'Respectful discussion matters even when decisions differ.']]},
 {place:'Back in Year 3 Bronze',icon:'🏆',npc:'👧',speaker:'Year 3 Bronze',q:'Mission 25! What is Hoorain’s final job after the meeting?',choices:[['Report back, thank the class and explain the next steps',3,2,'Mission complete! Hoorain listened, helped and represented Year 3 Bronze brilliantly.'],['Keep the meeting secret',0,0,'The class should know how their ideas were represented.'],['Only tell her closest friends',0,0,'A representative communicates with the whole class.']]}
]
let i=0,stars=0,kindness=0,sound=true;
const $=id=>document.getElementById(id);
function tone(freq=620){if(!sound)return;try{const a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.value=.04;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.12)}catch(e){}}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function award(text){const a=$('achievement');a.textContent=text;a.classList.remove('show');void a.offsetWidth;a.classList.add('show')}
function updateScore(){ $('stars').textContent=stars; $('kindness').textContent=kindness; }
function render(){
 const m=missions[i]; $('place').textContent=m.place;$('placeIcon').textContent=m.icon;$('npc').textContent=m.npc;$('speaker').textContent=m.speaker;$('question').textContent=m.q;$('feedback').textContent='';$('nextBtn').classList.add('hidden');$('progressFill').style.width=(i/missions.length*100)+'%';$('missionNo').textContent=i+1;$('missionTotal').textContent=missions.length;
 const c=$('choices'),ch=$('challenge'); c.innerHTML='';ch.innerHTML='';ch.classList.add('hidden');
 if(m.type==='stars') return starChallenge(ch);
 if(m.type==='find') return findChallenge(ch);
 m.choices.forEach((x,n)=>{const b=document.createElement('button');b.className='choice';b.textContent=x[0];b.addEventListener('click',()=>choose(n,b));c.appendChild(b)});
}
function choose(n,b){const x=missions[i].choices[n];document.querySelectorAll('.choice').forEach(z=>z.disabled=true);stars+=x[1];kindness+=x[2];updateScore();$('feedback').textContent=x[3];if(x[1]+x[2]>0){b.classList.add('good');award(x[2]>0?'❤️ Kindness earned!':'⭐ Leadership earned!');}tone();$('nextBtn').classList.remove('hidden')}
function starChallenge(ch){
 ch.classList.remove('hidden');ch.innerHTML='<p class="challenge-title">Tap all 5 stars!</p><div class="collect-zone" id="collectZone"></div><p class="mini-status" id="miniStatus">0 / 5 collected</p>';
 const zone=$('collectZone'),pos=[[8,18],[30,62],[51,25],[70,67],[86,18]];let got=0;
 pos.forEach((p,n)=>{const b=document.createElement('button');b.className='collect-star';b.textContent='⭐';b.style.left=p[0]+'%';b.style.top=p[1]+'%';b.setAttribute('aria-label','Collect star '+(n+1));b.addEventListener('click',()=>{if(b.disabled)return;b.disabled=true;got++;stars++;updateScore();$('miniStatus').textContent=got+' / 5 collected';tone(760);if(got===5){$('feedback').textContent='Amazing! You found every Leadership Star.';award('🌟 Star Hunt Complete!');$('nextBtn').classList.remove('hidden')}});zone.appendChild(b)});
}
function findChallenge(ch){
 ch.classList.remove('hidden');ch.innerHTML='<p class="challenge-title">Which item is Aisha’s yellow notebook?</p><div class="object-grid" id="objectGrid"></div><p class="mini-status" id="miniStatus">Look carefully!</p>';
 const items=[['🎒','Backpack'],['📘','Blue book'],['📒','Yellow notebook'],['✏️','Pencil'],['🧃','Juice'],['⚽','Ball']];
 items.forEach(([ico,name])=>{const b=document.createElement('button');b.className='object-btn';b.textContent=ico;b.setAttribute('aria-label',name);b.addEventListener('click',()=>{if(name==='Yellow notebook'){b.classList.add('found');b.disabled=true;kindness+=2;stars+=1;updateScore();$('miniStatus').textContent='Found it! Return it to Aisha.';$('feedback').textContent='Hoorain helped Aisha find her notebook.';award('❤️ Helpful Friend!');tone(800);document.querySelectorAll('.object-btn').forEach(x=>x.disabled=true);$('nextBtn').classList.remove('hidden')}else{$('miniStatus').textContent='Not that one — try again!';tone(300)}});$('objectGrid').appendChild(b)});
}
$('startBtn').addEventListener('click',()=>{i=stars=kindness=0;updateScore();show('play');render()});
$('nextBtn').addEventListener('click',()=>{i++;if(i>=missions.length){$('finalStars').textContent=stars;$('finalKindness').textContent=kindness;$('progressFill').style.width='100%';show('finish');tone(880)}else render()});
$('replayBtn').addEventListener('click',()=>show('start'));
$('soundBtn').addEventListener('click',()=>{sound=!sound;$('soundBtn').textContent=sound?'🔊':'🔇'});
